import json

SECRETS_PATH = 'secrets.json'

with open(SECRETS_PATH, 'r') as f:
    SECRETS = json.load(f)

SPARKPOST_API_KEY = SECRETS['SPARKPOST_API_KEY']
DEFAULT_RECIPIENTS = SECRETS['DEFAULT_RECIPIENTS']
DEFAULT_FROM_EMAIL = SECRETS['DEFAULT_FROM_EMAIL']
